### PR TITLE
Introduce special handling for multi-aspect containers

### PR DESCRIPTION
**Pull request by OneEyeMaker**
## Issues addressed by this PR
Current implementation of this mod hardcodes capacity of known essentia containers (because Thaumcraft API `IAspectContainer` provides no way to retrieve this value).
Also ThE considers that all containers share its capacity between different aspects (like Essentia reservoir). But there is at least one exception: Essentia condenser from Gadomancy which stores aspects independently.

## Goal
The goal of this PR is to provide clear way to handle containers that store essentia separately and/or have dynamic capacity. And thus resolve both mentioned issues.

---

This PR resolves [part](https://github.com/GTNewHorizons/Gadomancy/pull/27#issuecomment-1855452475) of issue of Essentia Condenser.

### CODE REVIEW

**Comment by boubou19** [comment]
isn't the new interface added required to be implemented in gadomancy to make this work?

**Comment by OneEyeMaker** [comment]
@boubou19 You got this right. I'm going to implement it in Gadomancy. But to do that I need to have ThE release with this feature as optional dependency. So this PR should be merged first.

**Comment by TechnicianLP** [comment]
From an architecture standpoint its kind of weird for that Interface to be part of ThE.
But since this is an issue stemming from the design of the Thaumcraft API its not easily fixed.

Since ThE already requires manualy registration of Aspect Containers for some reason, wouldnt it be possible to adapt the logic there? Instead of just being able to register an int as capacity one could register a interface to determine total/individual aspect capacity dynamically. 
Currently the condenser registered with 64 capacity and then magic happens at a later point and the registered capacity is ignored because the tile implements some interface.

If that logic is implemented in Gadomancy, the Logic for the other containers/tiles should also be moved there.

**Comment by OneEyeMaker** [comment]
@TechnicianLP 
The thing is that ThE *doesn't require* registration of containers. The mod [**hardcodes**](https://github.com/GTNewHorizons/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/common/integration/tc/EssentiaTileContainerHelper.java#L381) known containers itself.
And changing container's capacity directly to actual capacity or providing a way to register container with specific capacity don't solve issue completely. Because Essentia condenser from Gadomancy (for example) has *dynamic* capacity, i. e. its capacity can be changed/upgraded.
In result the idea I came up with is to query exact capacity of such specific container every time ThE interacts with one.

If you have any better idea - feel free to ping me in Discord.

**Comment by OneEyeMaker** [comment]
@TechnicianLP 
Thank you much for this idea. Its implementation allows to generalize handling of different aspect containers instead of *magically* changing logic for ones implementing specific interface.

**Comment by Alastors** [comment]
> @boubou19 You got this right. I'm going to implement it in Gadomancy. But to do that I need to have ThE release with this feature as optional dependency. So this PR should be merged first.

ping me when you do

**Review by Alastors — APPROVED** [review]
the code itself looks fine, couldn't be tested in pack since this needs to be merged before the gadomancy pr, though I should not I'm not particularly familiar with AE and ThE's codebases

**Review by TechnicianLP — APPROVED** [review]
Will break Gadomancy integration until a corresponding PR for Gadomancy is merged.
Otherwise looks fine as is.

Would have been nice though if implementing the new interface (with additional methods) was defacto registration. This could then be used to get rid of the indirect dependencies via Class.forName. The Issue may be independently tackled at a later point though

**Pull request merged**
