### PR TITLE
Added crafting status button to ThE terminals

### PR DESCRIPTION
**Pull request by Gregory1234**
This adds the "crafting status" button to the Arcane Terminal. I've tested it in singleplayer and in multiplayer. It works, except that there is no tooltip for the button, because ThE seems to do tooltips very differently than AE2. 
image
image

### CODE REVIEW

**Comment by Gregory1234** [comment]
Fixes GTNewHorizons/GT-New-Horizons-Modpack#9667
and partially GTNewHorizons/GT-New-Horizons-Modpack#16193

**Review by Alastors — APPROVED** [review]
I don't see anything particularly jarring so

**Comment by MCTBL** [comment]
The tooltip won't show up correctly because of use the button from ae.

**Comment by Dream-Master** [comment]
@MCTBL ok maybe can you make a pr fix that ?

**Comment by MCTBL** [comment]
And may swap the button sequence is better
| AE |  ThE |
| :---: |  :---: |
| image | image |

**Comment by MCTBL** [comment]
> @MCTBL ok maybe can you make a pr fix that ?

I'll make a pr to fix this temporary, after all ThE's GUI need swap the whole things to AE's widgets.

**Pull request merged**
