### PR TITLE
fix essentia cache monitoring void jars

### PR DESCRIPTION
**Pull request by repo-alt**
(also some warnings cleanup)
Fixes(https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6335)

### CODE REVIEW

**Review by Glease — APPROVED** [review]
Guess this is ok. Those Hashtable hurts my eyes though...

**Comment by repo-alt** [comment]
Tables with Aspect as a key? There are not that much aspects, so it is pretty much irrelevant I think

**Comment by Glease** [comment]
I mean Hashtable vs HashMap.

**Comment by repo-alt** [comment]
Ah, I believe hte author of this mod was very inexperienced in Java, hence all those comments explaining every step, unusual formatting, etc.

**Pull request merged**
