### PR TITLE
Add 256K to 16384K essentia cell for ThE

### PR DESCRIPTION
**Pull request by MCTBL**

### CODE REVIEW

**Comment by MCTBL** [comment]
256K Cell can hold 24 types.
1024K can hold 36 types.
4096K can hold 48 types.
16384K can hold 60 types.

**Comment by Dream-Master** [comment]
@MCTBL please add not ingots to recipes they looks so vanilla. Plates or other parts are much nicer.

**Comment by MCTBL** [comment]
> @MCTBL please add not ingots to recipes they looks so vanilla. Plates or other parts are much nicer.

This just for ThE itself. I will add other recipes for GTNH.

**Comment by MCTBL** [comment]
> How about using Essentia Reservoirs in the recipes of 16384K instead of the glass

Good idea, I will swap it later.

**Comment by MCTBL** [comment]
image

**Comment by MCTBL** [comment]
Add recipe to GTNH Core, check it here https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/758

**Review by Laiff — APPROVED** [review]

**Pull request merged**
