### PR TITLE
Make two provider can order essentia aspect automatic

### PR DESCRIPTION
**Pull request by MCTBL**
and fix spelling errors

### CODE REVIEW

**Comment by MCTBL** [comment]
Auto order with infusion provider
https://discord.com/channels/181078474394566657/603348502637969419/1256839162653310995

Auto order with essentia provider
https://discord.com/channels/181078474394566657/603348502637969419/1256847686787792916

**Review by Alastors — CHANGES_REQUESTED** [review]
Actually explain what you're doing exactly, this is not up to standard in proposal

**Comment by Alastors** [comment]
Oh wait you did in discord

**Review by Alastors — APPROVED** [review]
Not a huge fan of the method names, but code looks fine

**Comment by Alastors** [comment]
Next time put this information directly in the ticket instead of making us have to pull up discord, please

**Comment by MCTBL** [comment]
> Next time put this information directly in the ticket instead of making us have to pull up discord, please

Sry, I'll take care of it next time.

**Pull request merged**
